# Generated by Django 3.2.7 on 2021-09-04 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_rename_category_category_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='place',
            new_name='pic_type',
        ),
    ]
